server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://8.140.100.224:3306/myresource
    driver-class-name: com.mysql.jdbc.Driver
    username: myresource
    password: 1234

  # activiti default configuration
  activiti:
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/processes/
#    process-definition-location-suffixes:
#      - **.bpmn
#      - **.bpmn20.xml
    history-level: full

